name: snapfeast
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  dio:
  file_picker:
  flutter_riverpod:
  flutter_screenutil:
  device_preview:
  go_router:
  cached_network_image:
  flutter_spinkit:
  flex_color_scheme:
  equatable:
  flutter_boxicons:
  flutter_launcher_icons:
  flutter_native_splash:
  timeago:
  shared_preferences:
  flutter_svg:
  animated_switcher_plus:
  skeletonizer:
  dropdown_button2:
  animated_snack_bar:
  awesome_notifications:
  camera_camera:
  image:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_launcher_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter_native_splash:
  color: "#393939"
  android: true
  ios: true
  web: false

  image: "assets/images/logo.png"

  android_12:
    color: "#393939"




flutter:
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Black.ttf
         - asset: assets/fonts/Montserrat-Bold.ttf
         - asset: assets/fonts/Montserrat-ExtraBold.ttf
         - asset: assets/fonts/Montserrat-Light.ttf
         - asset: assets/fonts/Montserrat-Medium.ttf
         - asset: assets/fonts/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat-SemiBold.ttf
         - asset: assets/fonts/Montserrat-Thin.ttf
